### PR TITLE
Activate zram via OpenRC

### PR DESCRIPTION
**Pull request by dderby**

### CODE REVIEW

**Comment by sicelo** [comment]
On my N900, running `/etc/init.d/zram start` throws an error, but goes on to mount the zram device.
The error comes from line 23 of the /etc/init.d/zram which runs `modinfo zram.` The command fails with **"modinfo: ERROR: Module zram not found."** Of course the module exists.

**Comment by parazyd** [comment]
On Sun, 18 Feb 2018, Sicelo wrote:

>    On my N900, running /etc/init.d/zram start throws an error, but goes on
>    to mount the zram device.
>    The error comes from line 23 of the /etc/init.d/zram which runs modinfo
>    zram. The command fails with "modinfo: ERROR: Module zram not found."
>    Of course the module exists.

I believe this is rather due to the fact zram is builtin, not a
probeable module.

We can either edit the initscript (it's part of arm-sdk), or make zram a
kernel module.

Thoughts?

-- 
~ parazyd
GnuPG: 03337671FDE75BB6A85EC91FB876CB44FA1B0274
GnuPG: https://parazyd.cf/FA1B0274.asc

**Comment by dderby** [comment]
I saw the error too. The script continues to run as expected (`set -e` is not used).  I've no problem with either solution, although I noticed that most other platforms in the arm-sdk have it built as a module so we may want to do this on the N900 for consistency.  Droid 4 doesn't have CONFIG_ZRAM set yet.  I'll fix both N900 and Droid 4 config files to use modules if you agree.

**Comment by parazyd** [comment]
On Mon, 19 Feb 2018, dderby wrote:

>    I saw the error too. The script continues to run as expected (set -e is
>    not used). I've no problem with either solution, although I noticed
>    that most other platforms in the arm-sdk have it built as a module so
>    we may want to do this on the N900 for consistency. Droid 4 doesn't
>    have CONFIG_ZRAM set yet. I'll fix both N900 and Droid 4 config files
>    to use modules if you agree.

Sure, feel free to submit patches.

The N900 config is in our n9xx-linux repository:
https://github.com/maemo-leste/n9xx-linux/blob/pvr-wip/arch/arm/configs/rx51_defconfig

The droid4 config is in arm-sdk:
https://github.com/parazyd/arm-sdk/blob/master/boards/kernel-configs/droid4.config

**Pull request merged**
