### PR TITLE
Changes to build pinephone image

### PR DESCRIPTION
**Pull request by javiplx**

### CODE REVIEW

**Comment by parazyd** [comment]
Hi. Thank you for the PR.

Have you seen that we've switched to `beowulf` as the default release now? I have already built Pinephone images with it. Perhaps you should check that out :)

Unfortunately I don't think I can merge your commits to the master branch.

* a28a71bda85358787dbb9540bae1cc6327fe18fe
We already have `linux-image-pine64` in our repositories, and it will be installed with `hildon-meta-pinephone`.

* 393f9fb62bf1f2ae9528c091ab84850412442def
`-devel` is something to be used by developers locally, not be the default.

* b1d61b38f7782e37460b3ce92cf9293237a2a73b
Hildon and Maemo Leste default to landscape everywhere else, so I think the same should be happening on the Pinephone.

**Comment by MerlijnWajer** [comment]
Personally, I think we could default to portait on the pinephone, if most of the issues are ironed out.

**Comment by freemangordon** [comment]
I think we shouldn't default to anything, but teach mce to read the accelerometers ;)

**Comment by parazyd** [comment]
Closing since this has been integrated. Thanks.

**Pull request closed without merging**
