### PR TITLE
Fix expandcard.sh script

### PR DESCRIPTION
**Pull request by sicelo**
Tested fine on my N900 with a brand new image. Would appreciate someone verifying that all is well

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Could it be possible to parse the block that you need to place the partition at? I think we did something weird to align it to certain block boundaries, and we should make sure not to mess with that. Then again, IDN. @parazyd ?

**Comment by sicelo** [comment]
>  Could it be possible to parse the block that you need to place the partition at?

I don't know if I understand well, but if it means knowing where to place the start of the partition (partition 2), the script just makes it start wherever the one in the plain image started at, That is the purpose of the `start` variable, and for feeding its output to fdisk. Since we determine it after the image is in place, and running live, it sounds safe (to me).

But yes, scripts like these do seem scary at times, in case something will fail silently now, but cause big issues later.

**Comment by MerlijnWajer** [comment]
You're right about the `start` variable. I missed that.

**Comment by parazyd** [comment]
Looks fine to me. I'll merge it, thanks!

**Pull request merged**
